# M1 Joblib External M2 Performance Validation

M1에서 잠근 joblib 모델을 M2에 그대로 적용해 외부 테스트 성능을 계산한다.

In [1]:
import runpy
result = runpy.run_path('scripts/run_35_m1_joblib_external_m2_performance_validation.py')
result['main']()

{"external_rows": 298, "decisions": {"external_gate_pass": 3, "sensitivity_only_not_training_equivalent": 1, "external_gate_fail": 1}}

In [2]:
import pandas as pd
pd.read_csv('07_데이터산출물/m2_external_joblib_metrics.csv')

,dataset_id,gate,rows,positive_rows,normal_or_negative_rows,threshold,balanced_accuracy,precision,recall,f1,normal_fpr,tn,fp,fn,tp
0,m2_activity_pre_1d_external,activity_gate,57,27,30,0.5,1.000000,1.000000,1.00,1.000000,0.000000,30,0,0,27
1,m2_fault_internal_efd_possible_sensitivity,fault_pre_event_gate,39,25,14,0.6,0.605714,0.727273,0.64,0.680851,0.428571,8,6,9,16
2,m2_fault_no_overlap_external,fault_gate,75,45,30,0.5,0.866667,0.947368,0.80,0.867470,0.066667,28,2,9,36
3,m2_normal_vs_efd_possible_external,fault_pre_event_gate,55,25,30,0.6,0.520000,0.470588,0.64,0.542373,0.600000,12,18,9,16
4,m2_task_post_1d_external,task_gate,72,42,30,0.5,1.000000,1.000000,1.00,1.000000,0.000000,30,0,0,42

In [3]:
pd.read_csv('07_데이터산출물/m2_external_performance_decision_matrix.csv')

,dataset_id,gate,rows,positive_rows,normal_or_negative_rows,threshold,balanced_accuracy,precision,recall,f1,normal_fpr,tn,fp,fn,tp,decision,external_test_manufacturer,model_training_manufacturer,model_retrained_on_m2
0,m2_activity_pre_1d_external,activity_gate,57,27,30,0.5,1.000000,1.000000,1.00,1.000000,0.000000,30,0,0,27,external_gate_pass,manufacturer_2,manufacturer_1,False
1,m2_fault_internal_efd_possible_sensitivity,fault_pre_event_gate,39,25,14,0.6,0.605714,0.727273,0.64,0.680851,0.428571,8,6,9,16,sensitivity_only_not_training_equivalent,manufacturer_2,manufacturer_1,False
2,m2_fault_no_overlap_external,fault_gate,75,45,30,0.5,0.866667,0.947368,0.80,0.867470,0.066667,28,2,9,36,external_gate_pass,manufacturer_2,manufacturer_1,False
3,m2_normal_vs_efd_possible_external,fault_pre_event_gate,55,25,30,0.6,0.520000,0.470588,0.64,0.542373,0.600000,12,18,9,16,external_gate_fail,manufacturer_2,manufacturer_1,False
4,m2_task_post_1d_external,task_gate,72,42,30,0.5,1.000000,1.000000,1.00,1.000000,0.000000,30,0,0,42,external_gate_pass,manufacturer_2,manufacturer_1,False